snippets = [
"A determined programmer can write FORTRAN in any language",
"All these classes and layers are confusing, can't we jam it all into one method?",
"We need more UML diagrams",
"Best practices? No, we have our own unique way of using Subversion.",
"Fancy terms like 'patterns', 'unit tests' and 'abstraction' aren't used around here.",
"There's the right way, the wrong way, and our way. Do it our way.",
"No need to budget time for testing and debugging. Just write it correctly the first time!",
"I've got some really great ideas. All I need are some technical people to put the code together.",
"All programming languages are the same: Symbols and gibberish. Just pick one and stick with it.",
"Of course DataContextSessionContextRelationFactory implements IDataContextSessionContextRelationFactory!",
"Don't bother optimizing, we can just add another box to the cluster.",
"If we aren't going to meet the deadline, we can just bring in some of the guys from the other team to help.",
"I can just validate the URL with a regular expression! It will be easy.",
"I like to write everything myself, I don't trust third party libraries or anything open source.",
"If we need more disk space, just delete the log files.",
"I got tired of looking at all those compiler warnings, so I turned them off.",
"We're going to build the next Facebook, but it's going to be better than Facebook. We're gonna be rich!",
"They haven't made anything better than Object Pascal, and I don't think they ever will.",
"I'm just piping all the error messages to /dev/null. They were cluttering up the logs.",
"We don't use comments. The code should be self-documenting.",
"We're agile, we just don't really do sprints and our standups are always over an hour long.",
"Have you tried turning it off and turning it back on again?",
"It's not my fault my software runs out of memory. It's your fault for not installing more.",
"What do you mean programming is hard? It's all just ones and zeros.",
"The users are confused, can we rewrite the whole app to be an Excel spreadsheet?",
"Databases are no good. Store all the data in a file. Files are fast.",
"Passwords are too hard to remember. I just use the word 'password' so I never forget",
"If we prefix all the column names with the table name, the database becomes self-documenting!",
"We use git but I don't like it. We're all pushing directly to master but we keep running into conflicts.",
"I don't know how to get better quality code. I've heard good things about unit tests, but I don't use them.",
"I've never really used design patterns, but I feel like they're probably a waste of time.",
"Look, some methods are a few hundred lines long. It's not wrong, it's just the way things are.",
"We call it Agile, but it's basically Waterfall with more meetings",
"It doesn't matter what your commits are, just squash them all together",
"We don't use third-party software, we develop everything in house",
"We don't have time to test, but we never compromise on quality",
"There's a new Angular release, so we have to rewrite the whole app again"
];
